name: Lint

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - name: Install dependencies
        run: uv sync
      - name: Ruff check
        run: uv run ruff check --output-format=github
      - name: Ruff format check
        run: uv run ruff format --check
      - name: Type check
        run: uv run pyright
